### ISSUE TITLE
Allow admins to upload images

### ISSUE THREAD

**Issue by naoei** [naoei/VADB-Issue-Tracker#9]
Currently, URLs are being used for both the profile picture and the banner, the issue with this is that at times the artist might want to use another profile picture instead and as such the URL would become invalid. Letting the admins upload images themselves would circumvent this problem, however, I'm not sure if I should keep the URL text input still available and have it fetch and download the image at that time.

#8 Would also benefit from this.

**Comment by TNTzx** [comment]
i wonder if you could pull the pfp from youtube/soundcloud/etc.'s api instead, such that when they change pfps simply pulling from the api would get their updated pfp
i don't think image uploading would be nice because that would add some more data to store compared to a single url

maybe you could add the option of using a link / uploaded image / api uploaded image to add backwards compatibility

**Comment by naoei** [comment]
"More data" isn't an issue anymore, and as I've said before I'm thinking of keeping the text input there but instead it downloads the image from that URL instead.
